CREATE TABLE ARTISTAS (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR (100) NOT NULL,
    TIPO VARCHAR (20)NOT NULL,
    GENERO_MUSICAL VARCHAR(50),
    PAIS_ORIGEM VARCHAR (50),
    ANO_INICIO INT,
    MUSICA_ MAIS_OUVIDA VARCHAR (50),
    ATIVO BOOLEAN DEFAULT TRUE,
);

SELECT *TABLE